parser:
    url: http://donnees.roulez-eco.fr/opendata/jour
    directory: /home/axel/Programmation/WorkspacePython/parserRegionalGazPrices/out
postgresql:
    host: localhost
    port: 5432
    dbname: gazprices
    user: creator
    password: ""
